"""baseline_initial_schema

Revision ID: 1e20ab06a63c
Revises: 
Create Date: 2026-05-02 13:35:06.782418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.diary  # noqa: F401  — baseline 引用了 StringListJSON 等自定义类型


# revision identifiers, used by Alembic.
revision: str = '1e20ab06a63c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('mbti', sa.String(length=10), nullable=True),
    sa.Column('social_style', sa.String(length=20), nullable=True),
    sa.Column('current_state', sa.String(length=20), nullable=True),
    sa.Column('catchphrases', sa.JSON(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='student', nullable=False),
    sa.Column('counselor_info', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_email'), ['email'], unique=False)

    op.create_table('assistant_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('proactive_greeting_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('assistant_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('care_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shield_balance', sa.Integer(), nullable=False),
    sa.Column('last_reward_streak', sa.Integer(), nullable=False),
    sa.Column('shielded_dates', app.models.diary.StringListJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_care_statuses_user_id')
    )
    with op.batch_alter_table('care_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_statuses_user_id'), ['user_id'], unique=False)

    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('collect_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='0', nullable=False, comment='管理员隐藏标记'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_posts_circle_id'), ['circle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_user_id'), ['user_id'], unique=False)

    op.create_table('counselor_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=20), nullable=False, comment='申请的目标角色: counselor 或 psychologist'),
    sa.Column('real_name', sa.String(length=50), nullable=False, comment='真实姓名'),
    sa.Column('department', sa.String(length=100), nullable=False, comment='所属院系/单位'),
    sa.Column('employee_id', sa.String(length=50), nullable=True, comment='工号'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('qualification_images', sa.JSON(), nullable=True, comment='资质证明照片URL列表'),
    sa.Column('introduction', sa.Text(), nullable=True, comment='个人简介/申请说明'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='审核管理员ID'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counselor_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counselor_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_counselor_applications_user_id'), ['user_id'], unique=False)

    op.create_table('counselor_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False, comment='范围类型: department(院系) 或 class(班级)'),
    sa.Column('scope_name', sa.String(length=100), nullable=False, comment='范围名称，如: 计算机学院、软件工程2班'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counselor_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counselor_bindings_user_id'), ['user_id'], unique=False)

    op.create_table('counselor_weekly_digest_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counselor_weekly_digest_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counselor_weekly_digest_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counselor_weekly_digest_logs_week_start'), ['week_start'], unique=False)

    op.create_table('diaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('diary_date', sa.Date(), nullable=False),
    sa.Column('emotion_tags', app.models.diary.StringListJSON(), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('images', app.models.diary.StringListJSON(), nullable=True),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diaries_diary_date'), ['diary_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_diaries_user_id'), ['user_id'], unique=False)

    op.create_table('external_integration_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_hint', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_external_token_user_provider')
    )
    with op.batch_alter_table('external_integration_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_integration_tokens_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_integration_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_external_integration_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('growth_daily_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insight_date', sa.Date(), nullable=False),
    sa.Column('primary_emotion', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'insight_date', name='uq_growth_daily_user_date')
    )
    with op.batch_alter_table('growth_daily_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_growth_daily_insights_insight_date'), ['insight_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_growth_daily_insights_user_id'), ['user_id'], unique=False)

    op.create_table('social_post_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_post_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_post_samples_user_id'), ['user_id'], unique=False)

    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diary_id', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_diary_id'), ['diary_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('assistant_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assistant_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_messages_user_id'), ['user_id'], unique=False)

    op.create_table('post_collects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_post_collect')
    )
    with op.batch_alter_table('post_collects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_collects_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_collects_user_id'), ['user_id'], unique=False)

    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_comments_user_id'), ['user_id'], unique=False)

    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_post_like')
    )
    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_likes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_likes_user_id'), ['user_id'], unique=False)

    op.create_table('post_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_views_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_views_user_id'), ['user_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diary_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_summary', sa.String(length=500), nullable=False),
    sa.Column('emotion_tag', sa.String(length=50), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('related_entities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diaries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_emotion_tag'), ['emotion_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_emotion_tag'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('post_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_views_post_id'))

    op.drop_table('post_views')
    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_likes_post_id'))

    op.drop_table('post_likes')
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_comments_post_id'))

    op.drop_table('post_comments')
    with op.batch_alter_table('post_collects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_collects_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_collects_post_id'))

    op.drop_table('post_collects')
    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_assistant_messages_session_id'))

    op.drop_table('assistant_messages')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_diary_id'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('social_post_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_post_samples_user_id'))

    op.drop_table('social_post_samples')
    with op.batch_alter_table('growth_daily_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_growth_daily_insights_user_id'))
        batch_op.drop_index(batch_op.f('ix_growth_daily_insights_insight_date'))

    op.drop_table('growth_daily_insights')
    with op.batch_alter_table('external_integration_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_integration_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_external_integration_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_external_integration_tokens_provider'))

    op.drop_table('external_integration_tokens')
    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diaries_user_id'))
        batch_op.drop_index(batch_op.f('ix_diaries_diary_date'))

    op.drop_table('diaries')
    with op.batch_alter_table('counselor_weekly_digest_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counselor_weekly_digest_logs_week_start'))
        batch_op.drop_index(batch_op.f('ix_counselor_weekly_digest_logs_user_id'))

    op.drop_table('counselor_weekly_digest_logs')
    with op.batch_alter_table('counselor_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counselor_bindings_user_id'))

    op.drop_table('counselor_bindings')
    with op.batch_alter_table('counselor_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counselor_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_counselor_applications_status'))

    op.drop_table('counselor_applications')
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_posts_circle_id'))

    op.drop_table('community_posts')
    with op.batch_alter_table('care_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_statuses_user_id'))

    op.drop_table('care_statuses')
    with op.batch_alter_table('assistant_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_sessions_user_id'))

    op.drop_table('assistant_sessions')
    with op.batch_alter_table('assistant_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_profiles_user_id'))

    op.drop_table('assistant_profiles')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_email'))

    op.drop_table('verification_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
